### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by lxylxy123456** [matloff/omsi#5]
There is a command for view pdf in README.md, which is
`python OmsiGui.py xyx.edu 2000 me@abc.com "open xyz.pdf"`
However, the exam code is missing, which will cause the client to behave incorrectly, as Python is not receiving the command as `argv[5]`. 
A correct version should be
`python OmsiGui.py xyx.edu 2000 me@abc.com MT1 "open xyz.pdf"`

**Comment by matloff** [comment]
Thanks very much!
