### ISSUE TITLE
Feature request: automatic deletion of omsi_anwers

### ISSUE THREAD

**Issue by g-simmons** [matloff/omsi#6]
After taking an exam, the user has to manually delete their `omsi_answers` files from the master directory before taking the next test, otherwise they will be loaded as the user's current answers for the next test. This obviously won't go unnoticed by the user, but it is a minor inconvenience.

Perhaps on exiting the GUI, all `omsi_answers` files could have the current date and time appended to their filenames (to differentiate them), and these files could be moved to a `backup/` directory. Alternatively they could be placed in a subdirectory of `backup/`, where the subdirectory is named using the current date and time. Anything to move them out of the master directory so they aren't automatically loaded for the next test would be an improvement.

Cheers!

**Comment by matloff** [comment]
Very reasonable idea, though unfortunately not high priority.
